apiVersion: v1
kind: Pod
metadata:
  name: devicequery
spec:
  nodeName: edgeblazer-desktop
  containers:
  - name: nvidia
    image: xift/jetson_devicequery:r32.5.0
    command: [ "./deviceQuery" ]

