apiVersion: v1
kind: Pod
metadata:
  #name: nvidia-l4t-base
  name: ndevices
spec:
  restartPolicy: OnFailure
  #restartPolicy: Never
  containers:
  - name: nvidia-l4t-base
    #image: "nvcr.io/nvidia/l4t-base:r32.4.2"
    image: mario21ic/ndevices:jetson
    args:
       - /usr/local/bin/ndevices
    #   - /usr/local/cuda/samples/1_Utilities/deviceQuery/deviceQuery
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
        #nvidia.com/gpu: 1 # requesting 1 GPUs
        nvidia.com/gpu: 2 # requesting 2 GPUs
      limits:
        cpu: 200m
        memory: 500Mi
        #nvidia.com/gpu: 2

